### ISSUE TITLE
Missing auth() parameters

### ISSUE THREAD

**Issue by Duske** [auth0-developer-hub/api_nestjs_typescript_hello-world#1]
Hey auth0 team,

I got stuck with the missing parameters for the `auth()` call in: https://github.com/auth0-developer-hub/api_nestjs_typescript_hello-world/blob/eeb2ddc45b5d871017f6e3df41790856a55991b6/src/authorization/authorization.guard.ts#L28

Am i missing something or does this need to be fixed?

I simply went with

```ts
    const validateAccessToken = promisify(
      auth({
        issuerBaseURL: this.ISSUER_BASE_URL,
        audience: this.AUDIENCE,
      }),
    );
```

**Comment by fellmann** [comment]
If no options are specified, environment variables `ISSUER_BASE_URL`and `AUDIENCE` are used.

**Comment by Duske** [comment]
Thx!
